# -*- coding: utf-8 -*-
"""streamlit_MB_homepage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10V5XTc7GaJNUIRFSgvdXcMttg7guLB7b
"""

# Importation des bibliothèques

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# texte d'introduction

st.title("Analyse d'une base de données de voitures")

st.header("Réalisé par : Maxime Barski")